name: CI

on: [push, pull_request]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up sphinx
        run: |
          cd docs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          python setup.py install
      - name: Generate docs
        run: |
          cd docs
          make html
